/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Defaultfeedrate = number;
export type Terminal = boolean;
export type Windtype = "hoop";
export type Leadinmm = number;
export type Leadoutdegrees = number;
export type Lockdegrees = number;
export type Patternnumber = number;
export type Skipindex = number;
export type Skipinitialnearlock = boolean;
export type Windangle = number;
export type Windtype1 = "helical";
export type Mandrelrotation = number;
export type Windtype2 = "skip";
export type Layers = (HoopLayer | HelicalLayer | SkipLayer)[];
export type Diameter = number;
export type Enddiameter = number | null;
export type Windlength = number;
/**
 * Version of the .wind file format schema (1.x).
 */
export type SchemaVersion = string;
export type Thickness = number;
export type Width = number;

/**
 * Schema for FiberPath filament winding pattern definitions
 */
export interface WindDefinition {
  defaultFeedRate: Defaultfeedrate;
  layers: Layers;
  mandrelParameters: MandrelParameters;
  schemaVersion?: SchemaVersion;
  towParameters: TowParameters;
  [k: string]: unknown;
}
export interface HoopLayer {
  terminal?: Terminal;
  windType?: Windtype;
  [k: string]: unknown;
}
export interface HelicalLayer {
  leadInMM: Leadinmm;
  leadOutDegrees: Leadoutdegrees;
  lockDegrees: Lockdegrees;
  patternNumber: Patternnumber;
  skipIndex: Skipindex;
  skipInitialNearLock?: Skipinitialnearlock;
  windAngle: Windangle;
  windType?: Windtype1;
  [k: string]: unknown;
}
export interface SkipLayer {
  mandrelRotation: Mandrelrotation;
  windType?: Windtype2;
  [k: string]: unknown;
}
export interface MandrelParameters {
  diameter: Diameter;
  endDiameter?: Enddiameter;
  windLength: Windlength;
  [k: string]: unknown;
}
export interface TowParameters {
  thickness: Thickness;
  width: Width;
  [k: string]: unknown;
}
